### ISSUE TITLE
4a162fb update ba64949 異常

### ISSUE THREAD

**Issue by shihkefa** [andyching168/Smartdaily_Postal_HA#1]
嘗試過多種方式
1. HA跳出更新提示更新
2. 刪除smartdaily_postal_ha資料夾後重新安裝ba64949更新
3. 刪除整合實體+刪除smartdaily_postal_ha資料夾+刪除整合插件重新開機後重新安裝

方法1:原先4a162fb
正常運作實體，更新後直接變成不可用
方法2 & 3: 輸入金鑰後無實體出現
![messageImage_1707121000171](https://github.com/andyching168/Smartdaily_Postal_HA/assets/120175626/ebcc64c6-4268-4f63-bdb9-8050acafe770)

**Comment by andyching168** [comment]
經檢查是json有機會沒有 'postal_logisticsText'的資訊
已在 [b49a3d7](https://github.com/andyching168/Smartdaily_Postal_HA/commit/b49a3d75db5f49451cd4456760329aaafb0a359c)解決
